### ISSUE TITLE
Collab with Lia / 14.09.2023

### ISSUE THREAD

**Issue by cjmaxik** [cjmaxik/everyday-neuro-bingo#106]
- [x] New character definition
- - [x] Base definition
- - [x] Tally image
- - [x] Sounds
- - [x] Prompts
- [x] Stream definition (incl. routing)
- [x] Index menu entry
- [x] New / updated prompts
- [x] New / updated sounds
- [x] New free block image

**Comment by tioopental** [comment]
@cjmaxik should be good enough

**Comment by cjmaxik** [comment]
@tioopental sent some feedback

**Comment by tioopental** [comment]
![image](https://github.com/cjmaxik/everyday-neuro-bingo/assets/25345920/2b87b500-527a-41cd-8f23-8cc0d4af8cd3)
