### ISSUE TITLE
Different themes for the same collab partners

### ISSUE THREAD

**Issue by cjmaxik** [cjmaxik/everyday-neuro-bingo#17]
Some collab partners can have several themed collabs. For example, vedal can program and play games (ETS2 for example). We have to figure out how to address these streams with appropriate prompts.

**Comment by tioopental** [comment]
Based on https://discord.com/channels/574720535888396288/1072697081443131476/1113916992513134602 I think developing this idea might be waste of time

**Comment by cjmaxik** [comment]
:notlikethis:
Closing for now.
