### ISSUE TITLE
Board editor

### ISSUE THREAD

**Issue by cjmaxik** [cjmaxik/everyday-neuro-bingo#8]
For bigger streams (first collabs, debuts, etc.,) there should be a way to create the board manually, because randomness usually sucks.

**Comment by tioopental** [comment]
How about, for simplicity, just make the board take prompts for given collab from given file that has set amount of prompts, categorised between Neuro and someone, randomise them and asssing them to grid in a fixed way?

**Comment by cjmaxik** [comment]
My idea is:
- For first-time collabs, create a handpicked list to make the event stand out.
- For more recurring collabs (like filian's) create a collab list for random generation (50/50 split for each).

**Comment by tioopental** [comment]
Fair. What about first time collabs that are unannounced till the day they are scheduled?

**Comment by cjmaxik** [comment]
That's tough. But doable - we made Neuro x filian in several hours.

**Comment by cjmaxik** [comment]
Another thought - just make an indexed propmt list. It will be easier to do.

**Comment by cjmaxik** [comment]
Closed in favor of collab-specific prompt files.
