### ISSUE TITLE
anny subathon will actually end?

### ISSUE THREAD

**Issue by tioopental** [cjmaxik/everyday-neuro-bingo#81]
After timer changes, anny MIGHT be freed from her subathon, we'll need to prepare for it

- [ ] Upgrade and revision for Family Stream
- [ ] Upgrade and revision for Anny x Neuro
- [ ] Create Anny x Evil

**Comment by cjmaxik** [comment]
I mean, she can collaborate even on a subathon, so the revision is needed anyway.
