### ISSUE TITLE
Update Chat tally image

### ISSUE THREAD

**Issue by cjmaxik** [cjmaxik/everyday-neuro-bingo#86]
People say that the Chat tally image is hard to see. We need to find a better one.

[Current image](https://github.com/cjmaxik/everyday-neuro-bingo/blob/master/public/assets/images/neuro/chat.png): 
![](https://github.com/cjmaxik/everyday-neuro-bingo/blob/master/public/assets/images/neuro/chat.png?raw=true) 
![image](https://github.com/cjmaxik/everyday-neuro-bingo/assets/1501705/cdc460d6-d6fb-4427-86d1-3047be9ecf6a)

**Comment by tioopental** [comment]
![image](https://github.com/cjmaxik/everyday-neuro-bingo/assets/25345920/8f9d3b36-d9d4-472a-9d79-2bd2e12fbd5b)
Mabe this one?

**Comment by cjmaxik** [comment]
The same color palette, won't work/

**Comment by tioopental** [comment]
How about normal chatting?
![image](https://github.com/cjmaxik/everyday-neuro-bingo/assets/25345920/db348915-b554-4298-8a86-09b72f13a2ba)
